# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
