# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20151113_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='locality',
            new_name='municipality',
        ),
    ]
