# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-24 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20151116_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
    ]
