# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_remove_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='municipality',
            new_name='locality',
        ),
    ]
