# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20151111_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
