# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 19:11
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_id', models.CharField(max_length=8, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('cardholder_name', models.CharField(blank=True, max_length=64, null=True)),
                ('credit_card_type', models.CharField(blank=True, max_length=8, null=True)),
                ('credit_card_last_4', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('origin_ip_address', models.GenericIPAddressField()),
                ('authorized', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
