# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='purchase',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
