# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160414_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='orders.Order'),
        ),
    ]
