# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160314_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_card_last_4',
            new_name='payment_card_last_4',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_card_type',
            new_name='payment_card_type',
        ),
    ]
