# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160629_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_card_type',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Card Type'),
        ),
    ]
