# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160118_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping',
            new_name='shipping_cost',
        ),
    ]
