# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160315_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_card_expiration',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
