# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160118_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_addresss',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
    ]
