# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160719_0251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together=set([('state', 'district', 'county', 'city', 'postal_code')]),
        ),
    ]
