# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
        ('orders', '0005_auto_20160118_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='variant',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='products.Variant'),
            preserve_default=False,
        ),
    ]
