# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_transaction_payment_card_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_card_expiration',
            new_name='payment_card_expiration_date',
        ),
    ]
