# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20161018_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'verbose_name': 'Tax Rate'},
        ),
    ]
