# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 23:11
from __future__ import unicode_literals
import random

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160118_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_card',
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='{:08x}'.format(random.randrange(2**32)), max_length=8),
            preserve_default=False,
        ),
    ]
