# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20161018_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_of_goods_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
