# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='from_address',
            field=models.EmailField(default='contact@libreshop.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='subject',
            field=models.CharField(blank=True, max_length=998, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='to_address',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
