# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20160324_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='from_address',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='communication',
            old_name='to_address',
            new_name='to_email',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='content',
        ),
        migrations.AddField(
            model_name='communication',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
