# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20160324_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'created_at'},
        ),
    ]
