# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20160326_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
