# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_transaction_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='district',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
