# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0002_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variant'),
        ),
    ]
