# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variant_api_params'),
        ('carts', '0005_auto_20151031_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Variant'),
            preserve_default=False,
        ),
    ]
