# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 19:42
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=True, upload_to='images/product'),
        ),
    ]
