# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='drop_shipment_settings',
            new_name='fulfillment_settings',
        ),
    ]
