# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropshipmentsettingvalue',
            options={'verbose_name': 'drop shipment setting', 'verbose_name_plural': 'drop shipment settings'},
        ),
        migrations.RenameField(
            model_name='dropshipmentsettingvalue',
            old_name='setting',
            new_name='value',
        ),
    ]
