# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_manufacturer_filfillment_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='filfillment_period',
            new_name='fulfillment_period',
        ),
    ]
