# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160127_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropshipmentsettingvalue',
            old_name='drop_shipment_setting',
            new_name='setting',
        ),
        migrations.AlterUniqueTogether(
            name='dropshipmentsettingvalue',
            unique_together=set([('setting', 'variant')]),
        ),
    ]
