# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='api_params',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
