# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160213_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='fulfillment_period',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='fulfillment_time',
            field=models.TimeField(default=datetime.datetime(2016, 2, 15, 2, 33, 18, 110253, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
