# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0007_auto_20160528_0133'),
        ('products', '0004_auto_20160417_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_fulfillment_settings',
            field=models.ManyToManyField(blank=True, through='fulfillment.FulfillmentSettingValue', to='fulfillment.FulfillmentSetting'),
        ),
    ]
