# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160215_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='fulfillment_backend',
            field=models.CharField(default='django.core.mail.backends.locmem.EmailBackend', max_length=128),
            preserve_default=False,
        ),
    ]
