# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_default_fulfillment_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_fulfillment_settings',
            field=models.ManyToManyField(blank=True, through='fulfillment.FulfillmentSettingValue', to='fulfillment.FulfillmentSetting', verbose_name='Default Fulfillment Settings'),
        ),
    ]
