# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160528_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='fulfillment_settings',
            new_name='_fulfillment_settings',
        ),
    ]
