# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20160531_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
