# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_image_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='main',
            new_name='main_image',
        ),
    ]
