# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160531_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='main_image',
            new_name='featured',
        ),
    ]
