# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20160531_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
