# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='foo.png', max_length=255, upload_to='images/product'),
            preserve_default=False,
        ),
    ]
