# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20160601_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'updated'},
        ),
    ]
