# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160602_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'modified'},
        ),
    ]
