# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20160602_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.Variant'),
        ),
    ]
