# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 00:48
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20161020_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='variant',
            name='_cost_cache_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
