# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Baz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qux', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qux', models.ManyToManyField(through='contrib.Bar', to='contrib.Baz')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='baz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.Baz'),
        ),
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.Foo'),
        ),
        migrations.AlterUniqueTogether(
            name='bar',
            unique_together=set([('foo', 'baz')]),
        ),
    ]
