# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.Inventory')),
            ],
        ),
        migrations.RenameModel(
            old_name='Baz',
            new_name='Warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='bar',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bar',
            name='baz',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='qux',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='qux',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Bar',
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.Warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qux',
            field=models.ManyToManyField(through='contrib.Location', to='contrib.Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('inventory', 'warehouse')]),
        ),
    ]
