# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_auto_20160201_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
