# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 22:39
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warehouses',
            field=models.ManyToManyField(blank=True, through='inventory.Location', to='inventory.Warehouse'),
        ),
        migrations.AlterField(
            model_name='location',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Warehouse'),
        ),
    ]
