# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 16:15
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=django_measurement.models.MeasurementField(default=0, measurement_class='Mass'),
            preserve_default=False,
        ),
    ]
