# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 05:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160802_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
