# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 05:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160802_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='landed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True),
        ),
    ]
