# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160802_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='standard_unit_of_measure',
            field=models.CharField(choices=[('bg', 'bag'), ('bf', 'board feet'), ('bl', 'bale'), ('bt', 'bottle'), ('bx', 'box'), ('c', 'hundred'), ('cc', 'cubic centimeter'), ('cf', 'cubic feet'), ('ci', 'curie'), ('cl', 'cylinder'), ('cm', 'centimeter'), ('cn', 'can'), ('cs', 'case'), ('ct', 'carton'), ('cw', 'hundred weight'), ('cy', 'cubic yard'), ('di', 'diameter'), ('dr', 'drum'), ('dw', 'dewar'), ('dy', 'day'), ('dz', 'dozen'), ('ea', 'each'), ('ft', 'feet'), ('gl', 'gallon'), ('gm', 'gram'), ('gn', 'grain'), ('gr', 'gross'), ('hr', 'hour'), ('in', 'inch'), ('jr', 'jar'), ('kg', 'kilogram'), ('kt', 'kit'), ('la', 'lambda'), ('lb', 'pound'), ('lf', 'linear feet'), ('lg', 'length'), ('li', 'liter'), ('lt', 'lot'), ('ly', 'linear yard'), ('m', 'thousand'), ('mg', 'milligram'), ('ml', 'milliliter'), ('mm', 'millimeter'), ('mn', 'minute'), ('mo', 'month'), ('mr', 'micron'), ('mt', 'meter'), ('og', 'omega'), ('oz', 'ounce'), ('pa', 'package'), ('pc', 'piece'), ('pg', 'page'), ('pk', 'pack'), ('pl', 'pallet'), ('pr', 'pair'), ('pt', 'pint'), ('qr', 'quarter'), ('qt', 'quart'), ('rd', 'rod'), ('rl', 'roll'), ('rm', 'ream'), ('sf', 'square feet'), ('sh', 'sheet'), ('st', 'set'), ('sy', 'square yard'), ('tb', 'tube'), ('tr', 'transaction'), ('ut', 'unit'), ('vl', 'vial'), ('wk', 'week'), ('yd', 'yard'), ('yr', 'year')], default='ea', max_length=2),
        ),
    ]
