# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20161019_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='conversion_factor',
            field=models.CharField(max_length=32),
        ),
    ]
