# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 18:30
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventory_packed_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='packed_weight',
            field=django_measurement.models.MeasurementField(measurement_class='Mass', verbose_name='Packed Weight'),
        ),
    ]
