# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20161019_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventory.PurchaseOrder'),
        ),
    ]
