# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20161020_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total',
        ),
    ]
