# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 19:42
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20161021_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='purchasing_conversion_factor',
        ),
        migrations.AddField(
            model_name='inventory',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchasing Conversion Factor'),
        ),
    ]
