# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20161022_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='standard_unit_of_measure',
        ),
    ]
