# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 20:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20161022_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cost',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='packed_weight',
            field=django_measurement.models.MeasurementField(default=Decimal('0'), measurement_class='Mass', validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Packed Weight'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=django_measurement.models.MeasurementField(default=Decimal('0'), measurement_class='Mass', validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
