# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 22:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_supply_units_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='units_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True),
        ),
    ]
