# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 20:11
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20161101_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='packed_weight',
            field=django_measurement.models.MeasurementField(default=Decimal('0'), measurement_class='Mass', verbose_name='Packed Weight'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=django_measurement.models.MeasurementField(default=Decimal('0'), measurement_class='Mass'),
        ),
    ]
