# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipmentsettingvalue',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variant'),
        ),
        migrations.AddField(
            model_name='dropshipmentsetting',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fulfillment.Manufacturer'),
        ),
        migrations.AlterUniqueTogether(
            name='dropshipmentsettingvalue',
            unique_together=set([('setting', 'variant')]),
        ),
        migrations.AlterUniqueTogether(
            name='dropshipmentsetting',
            unique_together=set([('manufacturer', 'name')]),
        ),
    ]
