# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_auto_20160216_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='dropshipmentsetting',
            old_name='manufacturer',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='dropshipmentsetting',
            unique_together=set([('supplier', 'name')]),
        ),
    ]
