# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_auto_20160304_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillmentsettingvalue',
            options={'verbose_name': 'Fulfillment Setting', 'verbose_name_plural': 'Fulfillment Settings'},
        ),
    ]
