# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_auto_20160407_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
