# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 05:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0004_fulfillmentorder_fulfillmentpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='fulfillmentpurchase',
            name='shipping',
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='fulfillmentpurchase',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='fulfillmentpurchase',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
