# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0005_auto_20160416_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentorder',
            name='order_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='ID'),
        ),
    ]
