# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0007_auto_20160528_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillmentsettingvalue',
            options={},
        ),
    ]
