# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0011_auto_20160718_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
