# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import fulfillment.models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0012_auto_20160718_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='token',
            field=models.CharField(default='1234', max_length=8, unique=True),
        ),
    ]
