# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import fulfillment.models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0013_shipment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='token',
            field=models.CharField(default=fulfillment.models.get_token, max_length=8, unique=True),
        ),
    ]
