# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0016_carrier_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='unit_of_measure',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('oz', 'oz'), ('lb', 'lb')], max_length=2, verbose_name='Preferred Unit of Measure'),
        ),
    ]
