# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0017_auto_20160727_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentpurchase',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Purchase'),
        ),
    ]
