# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_cart_variant'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='selected_products',
            field=models.ManyToManyField(through='carts.Cart', to='products.Variant'),
        ),
    ]
