# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='selected_products',
            field=models.ManyToManyField(through='carts.Cart', to='products.Variant'),
        ),
    ]
