# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
